### ISSUE TITLE
change model after solve, then resolve

### ISSUE THREAD

**Issue by leethargo** [leethargo/CSIP#2]
This doesn't work properly, with the current implementation.

I noticed while testing the setting of objective sense. After the solve is finished, we still have the transformed problem, it seems. When setting another objective sense and calling `solve` again, nothing happens (the old solution is still considered optimal).

My workaround here was to call `SCIPfreeTransform()` before changing the objective sense. But this would need to be done before any change of the model (add var, add cons, change bound...) and looks horrible.

**Comment by fserra** [comment]
This is a bit random, but:

there is this warning in the [SCIPcreateVarBasic](http://scip.zib.de/doc/html/scip_8h.php#ac0121ed98c509e16fbc4db2bc56cfb51) docu

To get the objective value correctly, we may use SCIPgetBestSol and then SCIPgetSolOrigObj or SCIPgetSolTransObj depending on the stage we are.

What about solving the transformed before calling solve?
```
CSIP_RETCODE CSIPsolve(CSIP_MODEL* model)
{
   SCIP_in_CSIP( SCIPfreeTransform(model->scip));
   SCIP_in_CSIP( SCIPsolve(model->scip) );

   return CSIP_RETCODE_OK;
}
```

**Comment by leethargo** [comment]
OK, so I got an error, because I was using wrong methods (w.r.t. to solving stage) to query the objective value, apparently.

What would it help to call `freeTransform` *before* `solve`? My expectation is, that `solve` will trigger the transformatioanotn, so it's actually a no-op.

**Comment by fserra** [comment]
`SCIPfreeTransform` is going to change the stage to `PROBLEM` (we are never in `INIT`, because we create a problem as soon as we create `SCIP` and users can't free problems)... as you said, if you do `SCIPsolve` twice it will do nothing the second time.. calling `SCIPfreeTransform` will change the stage and then the second time you call `SCIPsolve` it will do something.

**Comment by leethargo** [comment]
I see what you mean. But can I still add constraints after `solve`?

**Comment by leethargo** [comment]
Doesn't work though, I would now get now get 
> [src/scip/scip.c:403] ERROR: cannot call method <SCIPsetObjsense> in problem solved stage

**Comment by fserra** [comment]
according to the docu, no you can't.
What would we lose if we call `freeTransform` after solve?

**Comment by leethargo** [comment]
I'm testing it right now, and replaced `getPrimalBound` with `getSolOrigObj(getBestSol)`. There are no SCIP errors now, but I think the `getBestSol` does not understand changes in the objective sense :confused:

**Comment by fserra** [comment]
but what would you expect? if you change the sense, you have to optimize again

**Comment by leethargo** [comment]
Of course. In the test (`test_lazy`), we change the sense, and *then* call solve. Maybe the issue is another one.

**Comment by leethargo** [comment]
I can't figure it out. According to the log output, the correct solution is found (with value 2.5), but when I ask for the objective value it's 0.0, for the solution (0.0, 0.0) and *not* (1.0, 2.0).

```
### added lazy constraint!
feasible solution found by trivial heuristic after 0.0 seconds, objective value 1.500000e+00
presolving:
(round 1, fast)       0 del vars, 0 del conss, 0 add conss, 1 chg bounds, 0 chg sides, 0 chg coeffs, 0 upgd conss, 0 impls, 0 clqs
(round 2, fast)       1 del vars, 0 del conss, 0 add conss, 1 chg bounds, 0 chg sides, 0 chg coeffs, 0 upgd conss, 0 impls, 0 clqs
   (0.0s) probing cycle finished: starting next cycle
presolving (3 rounds: 3 fast, 1 medium, 1 exhaustive):
 1 deleted vars, 0 deleted constraints, 0 added constraints, 1 tightened bounds, 0 added holes, 0 changed sides, 0 changed coefficients
 0 implications, 0 cliques
presolved problem has 2 variables (1 bin, 1 int, 0 impl, 0 cont) and 0 constraints
transformed objective value is always integral (scale: 0.5)
Presolving Time: 0.01
transformed 1/2 original solutions to the transformed problem space

### added lazy constraint!
 time | node  | left  |LP iter|LP it/n| mem |mdpt |frac |vars |cons |cols |rows |cuts |confs|strbr|  dualbound   | primalbound  |  gap   
t 0.0s|     1 |     0 |     0 |     - | 192k|   0 |   - |   2 |   0 |   0 |   0 |   0 |   0 |   0 |      --      | 2.500000e+00 |    Inf 
### added lazy constraint!
  0.0s|     1 |     0 |     0 |     - | 192k|   0 |   0 |   2 |   0 |   2 |   0 |   0 |   0 |   0 | 3.000000e+00 | 2.500000e+00 |  20.00%
### added lazy constraint!
  0.0s|     1 |     0 |     0 |     - | 193k|   0 |   0 |   2 |   1 |   2 |   0 |   0 |   0 |   0 | 3.000000e+00 | 2.500000e+00 |  20.00%
(run 1, node 1) restarting after 2 global fixings of integer variables

presolving:
presolving (1 rounds: 1 fast, 0 medium, 0 exhaustive):
 2 deleted vars, 0 deleted constraints, 0 added constraints, 0 tightened bounds, 0 added holes, 0 changed sides, 0 changed coefficients
 0 implications, 0 cliques
Presolving Time: 0.01

SCIP Status        : problem is solved [optimal solution found]
Solving Time (sec) : 0.01
Solving Nodes      : 0 (total of 1 nodes in 2 runs)
Primal Bound       : +2.50000000000000e+00 (4 solutions)
Dual Bound         : +2.50000000000000e+00
Gap                : 0.00 %
### objval = 0.000000 
### sol: 0.000000, 0.000000
test: /home/rs/src/CSIP/test/test.c:336: test_lazy: Assertion `fabs(solution[0] - 1.0) <= 1e-5' failed.
```

**Comment by fserra** [comment]
can you push? or create a branch, so I can see it plz

**Comment by leethargo** [comment]
Yes, on branch `freeTransform`.

**Comment by fserra** [comment]
Ok, the `freeTransform` kills the best solution....

**Comment by fserra** [comment]
Apparently, the best solutions in the transformed problem are only copied in a candidate pool, which `SCIP` will check at the next sol (or presol), but not in `PROBLEM` stage

1. We can store the solution ourselves
2. Call `SCIPfreeTransform` in all methods that modify the problem

I (Robert) personally prefer the first option

**Comment by mlubin** [comment]
Do we have a test that covers changing the model and resolving_

**Comment by leethargo** [comment]
Yes, the one where I change the optimization sense (and back).

**Comment by fserra** [comment]
the bug is fixed by f6b7ba2  and a3cc475

**Comment by leethargo** [comment]
Sorry, still broken. Apparently the solution is still lost after `freeTransform`.

**Comment by fserra** [comment]
so this is a bug on the `SCIP` side. The solution is actually not lost after the `freeTransform`. After `freeTransform`, `SCIP` will copy the solutions to the original problem. However, `SCIP` sorts the solution by objective value assuming **always** that less is better

A possible fix (on the `SCIP` side) is to reverse the order of the solution if the problem is maximization.

A possible fix (on the `CSIP` side) is to ask for the last solution instead of the bestSol, when problem is maximization

**Comment by leethargo** [comment]
I prefer fixes on the CSIP side, but is asking for the last solution really robust?

My last commit proposes a workaround, where we do the reformulation to "minimization" in CSIP. However, it still doesn't work for the tests where we solve multiple, modified problems.

Maybe we should clear the solution pool just before doing a `SCIPsolve`?

**Comment by fserra** [comment]
why wouldn't it work if you change to minimize????

it might make sense to clear the solution pool, though it might affect the
resolve making it slower

**Comment by leethargo** [comment]
The failing test `objsense`  first minimizes then maximizes a problem. I have not looked into it deeply, but I'm guessing that the solution from the first run has a value smaller than the negated value of the second run's solution.

**Comment by leethargo** [comment]
I guess clearing the solution pool would be `SCIPprimalFree`, but that is not public, and I don't think it will be resurrected with a new solve.

**Comment by leethargo** [comment]
Of course, we could still go back to the workaround of storing our own solution, next to the status.

**Comment by fserra** [comment]
you can probably go through all sols and call SCIPfreeSol

I don't like storing the solution

but this is weird, it should be failing let me have a look

**Comment by fserra** [comment]
okay, so it is failing because:

1) problem is minimize x ---> solving just solves
2) change to max --->problem is maximize x ----> solving changes to minimize -x and solve
3) change to min ----> problem is minimize -x -----> solving just solves

In 2) at the end, you should reset your changes ;)

**Comment by leethargo** [comment]
OK, I shouldn't code before breakfast ;-)
